# Setup
title:               CirrusSecure
tagline:             'A site prototype in search of a purpose'
description:         'Any suggestions?'
url:                 https://cirrussecure.github.io/
baseurl:             'proto1'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              CirrusSecure
  url:               https://cirrussecure.github.io/
  email:             cirrus.secure@gmail.com

# Gems
plugins:
  - jekyll-paginate

# ----------
# Source for following; 
# https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site

# lsi: false
safe: true
# source: [cirrussecure.github.io]
incremental: false
# highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
